server:
  port: 0
spring:
  output:
    ansi:
      enabled: ALWAYS
  # DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: dbuser
    password: 12345
  # SQL
  sql:
    init:
      mode: always
      continue-on-error: false
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      default_schema: warehouse
logging:
  level:
    ru:
      practicum:
        smart: INFO
    org:
      Zalando:
        logbook: TRACE