server:
  port: 0
spring:
  output:
    ansi:
      enabled: ALWAYS
  # DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/commerce
    username: dbuser
    password: 12345
  # SQL
  sql:
    init:
      mode: always
      continue-on-error: false
      schema-locations: classpath:/DB/DDL/schema.sql
      data-locations: classpath:/DB/Init/data.sql
  # JPA
  jpa:
    hibernate:
      ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true
      default_schema: shopping_store
logging:
  level:
    ru:
      practicum:
        smart: INFO
    org:
      Zalando:
        logbook: TRACE