name: Smart Home Tech Tests

on:
  workflow_dispatch:
    inputs:
      verbose_mode:
        description: "Включить подробные логи во время тестов"
        required: true
        default: true
        type: boolean
      print_logs:
        description: "Включить вывод логов в консоль"
        required: true
        default: true
        type: boolean
  pull_request:
    inputs:
      verbose_mode:
        required: true
        type: string
        default: "true"
      print_logs:
        required: true
        type: string
        default: "true"

jobs:
  build:
    uses: yandex-praktikum/plus-smart-home-tech/.github/workflows/api-tests.yml@ci
    with:
      verbose_mode: ${{ inputs.verbose_mode }}
      print_logs: ${{ inputs.print_logs }}
